Input validation functions jimmy
chingu-voyages/v47-tier1-team-01 pull request #26
Opened 2024-01-23 06:58 UTC by JimTK16

I have added the validation into the save() function. 
The rules are:
- Task Name cannot be empty or longer than 40 chars.
- Task Description can be empty but no longer than 100 chars.

I also modified the app title in the index.html to 'Daily Tasks App' instead of 'Document'.

Note: on naming variables, I think it will be clearer if we add 'El' (Element) at the end of the variables' name. So instead of 'taskName', we can use 'taskNameEl' and the 'taskName' will be used for the actual value inside the taskName Element. Like:
const taskName = taskNameEl.value

Jimmy

2024-01-23 14:05 UTC, andreimaier reviewed
Could you maybe put the code inside a separate function and then call that function inside `function saveTask(e)` ?

2024-01-23 14:11 UTC, andreimaier commented on public/index.js
> +    taskDescriptionErrorEl.innerHTML =
maybe use `.textContent` instead? Just generally safer than `innerHTML` or `innerText` I think

2024-01-23 14:18 UTC, andreimaier requested changes
I like the idea of using `taskNameEl` for variables that match HTML elements but not sure we need to declare another variable instead of just saying `.value`. But I can try to follow this convention if you want ! 😺 

- Please organize the code in a separate function
- Please look into sanitizing the content. I'll send you some ideas on discord
- see if you want to change `.innerHTML` to `.textContent`

2024-01-24 00:46 UTC, jeru7 approved these changes
I approved this since I don't see any problem. But just like what andrei said, you can use textContent or maybe innerText for safety purposes. Though ig you can stick with innerHtml since it's just for error messages but it will be a good practice to use textContent.

2024-01-24 01:29 UTC, andreimaier commented
> I approved this since I don't see any problem. But just like what andrei said, you can use textContent or maybe innerText for safety purposes. Though ig you can stick with innerHtml since it's just for error messages but it will be a good practice to use textContent.

Yes, Like @jeru7 said, here it's not absolutely neccessary to stay away from innerHTML. But please think about sanitizing input and move the code into a separate function, `saveTask()` is getting bloated already

2024-01-24 04:21 UTC, JimTK16 commented
I have attempted to use DOMPurify to sanitize user input. I'm not sure i'm doing it the correct way though. I did some reading and also used Bing AI. To use DOMPurify, i added a <script> tag in index.html and use the sanitize() function in index.js.

2024-01-24 05:13 UTC, andreimaier approved these changes

2024-01-24 05:15 UTC, andreimaier commented
The sanitizer you implemented works perfectly, good work! 

You can check it with dirty HTML ... input **<img src=x onerror=alert(1)>** into the input and you'll see in the console that it removes some part of it 

Please resolve the merge conflicts and then merge your branch!
If you're not sure how to do it, maybe @jeru7 can help you, he's the ***Merge Conflict Master Solver***

2024-01-24 06:31 UTC, merged